object FCarregaBPL: TFCarregaBPL
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'FCarregaBPL'
  ClientHeight = 27
  ClientWidth = 76
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
end
